spring:
  profiles:
    active: dev
  freemarker:
    cache: false
    charset: UTF-8
#    allow-request-override: false
#    allow-session-override: false
#    check-template-location: true
#    content-type: text/html
#    enabled: true
#    expose-request-attributes: false
#    expose-session-attributes: false
#    expose-spring-macro-helpers: true
#    prefer-file-system-access: true
#    suffix: .ftl
#    template-loader-path: classpath:/templates/
#    settings:
#        template_update_delay: 0
#        default_encoding: UTF-8
#        classic_compatible: true
server:
  port: 8888
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml